# Copyright (c) 2021 Concurrent Technologies Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software is distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing permissions and limitations under the License.

---
name: Scala
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linux-mac:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.16.x'

      - name: Build Î©edit
        run: |
          rm -rf build || true
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=YES -DBUILD_DOCS=OFF
          cmake --build build --target omega_edit
          cmake --install build --prefix "${PWD}/_install"
          mv _install/lib/* ./lib

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8

      - name: Setup SBT
        run: |
          curl -LO https://github.com/sbt/sbt/releases/download/v1.6.2/sbt-1.6.2.tgz
          sudo tar xvzf sbt-1.6.2.tgz -C /usr/local --strip-components=1
        working-directory: /tmp

      - name: Check Scala headers
        if: startsWith(matrix.os, 'ubuntu')
        run: sbt headerCheckAll
        working-directory: src/bindings/scala

      - name: Package Scala API and Linux so
        if: startsWith(matrix.os, 'ubuntu')
        run: sbt +test +publishM2
        working-directory: src/bindings/scala

      - name: Package Mac dylib
        if: startsWith(matrix.os, 'mac')
        run: sbt +test +native/publishM2
        working-directory: src/bindings/scala

      - name: Archive M2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-artifacts
          path: ~/.m2/repository/com/ctc/*
          if-no-files-found: error

      - name: Coverage report
        if: startsWith(matrix.os, 'ubuntu')
        run: sbt howMuchCoverage
        working-directory: src/bindings/scala

      - name: Build Scala gRPC Reference Impl
        if: startsWith(matrix.os, 'ubuntu')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt test
        working-directory: src/rpc/server/scala
